%% -*- mode: erlang -*-
%% -*- tab-width: 4;erlang-indent-level: 4;indent-tabs-mode: nil -*-
%% ex: ts=4 sw=4 sts ft=erlang et

case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        [{deps, [
            {rekt, {git, "https://github.com/nitrogen/rekt",  {branch, master}}},
            {simple_bridge, {git, "https://github.com/nitrogen/simple_bridge", {branch, master}}},
            {nitro_cache, {git, "https://github.com/nitrogen/nitro_cache", {branch, master}}},
            {nprocreg, {git, "https://github.com/nitrogen/nprocreg", {branch, master}}},
            {canister, {git, "https://github.com/nitrogen/canister", {branch, master}}},
            {erlang_ds, {git, "https://github.com/choptastic/erlang_ds", {branch, master}}},
            {qdate, {git, "https://github.com/choptastic/qdate", {branch, master}}}
        ]} | lists:keydelete(deps, 1, CONFIG)]
end.
