# vim: ts=3 sw=3 et ft=org
#+TITLE: Datepicker Textbox Element
#+STYLE: <LINK href='../stylesheet.css' rel='stylesheet' type='text/css' />
#+AUTHOR: Rusty Klophaus (@rustyio)
#+OPTIONS:   H:2 num:1 toc:1 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+EMAIL: 
#+TEXT: [[http://nitrogenproject.com][Home]] | [[file:../index.org][Getting Started]] | [[file:../api.org][API]] | [[file:../elements.org][*Elements*]] | [[file:../actions.org][Actions]] | [[file:../validators.org][Validators]] | [[file:../handlers.org][Handlers]] | [[file:../config.org][Configuration Options]] | [[file:../advanced.org][Advanced Guides]] | [[file:../troubleshooting.org][Troubleshooting]] | [[file:../about.org][About]]

* Datepicker Textbox Element - #datepicker\_textbox {}

  The datepicker textbox element produces an HTML textbox that automatically
  pops up a [[http://jqueryui.com/datepicker/][jQuery UI Datepicker]] when the
  control takes the focus.

** Usage

#+BEGIN_SRC erlang
   #datepicker_textbox{
      id=date1,
      text="5/25/2013",
      options=[
         {dateFormat, "mm/dd/yy"},
         {showButtonPanel, true}
      ]
   }
#+END_SRC

** Attributes

   + text - (/string/) :: Set the textbox's contents.

   + html\_encode - (/boolean/) :: Set to true to safely html-encode the text.

   + options - (/list of {Key,Value} properties/) :: Set the jQuery UI options. You can view the full
      list of options at the official [[http://api.jqueryui.com/datepicker/][jQuery UI Datepicker API Documentation]].
      Here are a few common options:

     * formatDate - (/format string/) :: Change the format of the displayed
         date (e.g.: ="yy-mm-dd"=, ="mm/dd/yy"= ).

     * showOtherMonths - (/boolean/) :: Set to true to allow the datepicker to
         show the previous and next month's last and first days in the otherwise
         blank spaces.

     * selectOtherMonths - (/boolean/) :: If =showOtherMonths= is true, then
         clicking those leading and trailing dates will also put the date in the
         textbox.

     * numberOfMonths - (/integer/) :: Display the specified number of months
         in the calendar popup rather than just a single month.

     * changeMonth - (/boolean/) :: Put a "Month" dropdown box in the calendar
         popup

     * changeYear - (/boolean/) :: Put a "Year" dropdown box in the calendar
         popup

     * showButtonPanel - (/boolean/) :: Put a button panel below the calendar
         popup which includes a "Today" button, and a "Close" button (the text of
         which [[http://api.jqueryui.com/datepicker/#option-showButtonPanel][can be customized]].

   + disabled - (/boolean/) :: Set to true to disable this textbox in the
      browser (sets the HTML =disabled= property, effectly greying out the
      element). Can be dynamically re-enabled with =wf:enable(ElementID)= or
      =wf:wire(ElementID, #enable{})= (Default: =false=)

   + readonly - (/boolean/) :: Set to true to make this element readonly in the
      browser. Can be toggled with =wf:wire(ElementID, #make_writable{})= and
      =wf:wire(ElementID, #make_readonly{})=.

   + placeholder - (/string/) :: Sets the placeholder text (text that will be
      in the textbox until the user focuses in the textbox). This uses the
      HTML5 placeholder attribute, which is only supported in newer browsers.
      To add support for older-browsers, you will need to link a placeholder
      script in your template. You can do this by adding the following to your
      template inside the =<head>= section after loading jQuery. 

#+BEGIN_SRC html
   <script src='/nitrogen/jquery.placeholder.js' type='text/javascript'></script>
#+END_SRC

   + next - (/atom/) :: If set with a valid control ID, pressing the enter key
      in the textbox will automatically move focus to the specified control.

   + postback - (/Erlang term/) :: If set, pressing the enter key in the
      textbox will automatically initiate a Nitrogen postback with the supplied
      term.

   + html\_name - (/string/) :: The name attribute of the textbox.

** See Also

   + [[./base.html][base element]]

   + [[./button.html][button element]]

   + [[./password.html][password element]]

   + [[./textarea.html][textarea element]]

   + [[./checkbox.html][checkbox element]]

   + [[./dropdown.html][dropdown element]]

   + [[./option.html][option element]]

   + [[http://nitrogenproject.com/demos/simplecontrols][Simple Controls Demos]]
 
