# vim: ft=org sw=3 ts=3 et
#+TITLE: Mobile Collapsible Set Element
#+STYLE: <LINK href='../stylesheet.css' rel='stylesheet' type='text/css' />
#+AUTHOR: Jesse Gumm (@jessegumm)
#+OPTIONS:   H:2 num:1 toc:1 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+EMAIL: 
#+TEXT: [[http://nitrogenproject.com][Home]] | [[file:../index.org][Getting Started]] | [[file:../api.org][API]] | [[file:../elements.org][*Elements*]] | [[file:../actions.org][Actions]] | [[file:../validators.org][Validators]] | [[file:../handlers.org][Handlers]] | [[file:../config.org][Configuration Options]] | [[file:../advanced.org][Advanced Guides]] | [[file:../troubleshooting.org][Troubleshooting]] | [[file:../about.org][About]]

* Mobile Collapsible Set Element - #mobile\_collapsible\_set {}

  This element produces a
  [[http://api.jquerymobile.com/collapsible-set/][Mobile Collapsible Set]]
  Element, which groups together =#collapsible= elements into a single unified
  structure.  The resulting collapsibles will then close any open collapsibles
  when another within the same group is opened.

** Usage

#+BEGIN_SRC erlang
   #mobile_collapsible_set { 
      collapsed=true,
      body=[
         #collapsible{ ... },
         #collapsible{ ... },
         #collapsible{ ... }
      ]
   }
#+END_SRC

** Attributes
   
   + header\_theme - (/atom/) :: Set the jQuery Mobile swatch letter for the contained #collapsible{} elements' header.

   + content\_theme - (/atom/) :: Set the jQuery Mobile swatch letter for the contained #collapsible{} elements' content.
   
   + mini - (/boolean/) :: Set to true to render the contained #collapsible{} elements in a smaller, more compact form.

** See Also

   + [[./jquery_mobile.html][jQuery mobile elements]]

   + [[./base.html][base element]]

   + [[./mobile_collapsible.html][mobile\_collapsible element]]

   + [[http://nitrogenproject.com/demos/mobile_collapsibles][Mobile Collapsible Demos]]
