# vim: ts=2 sw=2 et ft=org
#+STYLE: <LINK href="stylesheet.css" rel="stylesheet" type="text/css" />
#+TITLE: Nitrogen Plugins
#+AUTHOR: Jesse Gumm (@jessegumm)
#+OPTIONS:   H:2 num:1 toc:1 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+EMAIL: 
#+TEXT: [[http://nitrogenproject.com][Home]] | [[file:./index.org][Getting Started]] | [[file:./api.org][API]] | [[file:./elements.org][Elements]] | [[file:./actions.org][Actions]] | [[file:./validators.org][Validators]] | [[file:./handlers.org][Handlers]] | [[file:./config.org][Configuration Options]] | *Plugins* | [[file:./jquery_mobile_integration.org][Mobile]] | [[file:./troubleshooting.org][Troubleshooting]] | [[file:./about.org][About]]
#+HTML: <div class=headline>Nitrogen Plugins</div>

* Plugins Overview

  Nitrogen 2.2.0 introduced a plugin system for including Nitrogen elements,
  actions, validators, modules, handlers, and static resources from external
  sources (typically as rebar dependencies).

  Generally speaking, this provides for a simpler way of handling additional
  modularity, by creating custom reusable elements that can be shared between
  applications and/or other programmers.

* Adding a plugin to your app

  The simplest way to include a plugin in your app is to include it as a rebar
  dependency. In the =deps= section of your rebar.config file, add something
  like the following:

#+BEGIN_SRC erlang
  {my_plugin, ".*", {git, "git://github.com/user/my_plugin.git", {branch, master}}},
#+END_SRC

  Then run `make` in your application. It will download the plugin, add to your
  plugins.hrl file a reference to any include files (.hrl files), copy any
  static resources into your application's directory structure, and finally
  recompile everything.

** What happens when you add a plugin to your app

   The Nitrogen Plugin installer does a handful of things to your Application
   directory structure.  Any static resources are automatically copied into a
   =site/static/plugins/<pluginname>= directory.  Any Erlang includes (.hrl
   files) are added as =-include= calls to the =site/include/plugins.hrl= file.
   And, of course, being an Erlang dependency, the source code for the plugin
   will be automatically loaded.

   The directories above can all be customized with the plugins.config file
   found in the root of your Nitrogen release (see the "plugins.config" section
   of [[file:./config.org][Configuration Options]] for how to customize your
   plugin configuration.

* Finding plugins to include in your app

  Currently, the list of available plugins are found on our
  [[https://github.com/nitrogen/nitrogen/wiki/Nitrogen-Plugins][Plugins Wiki Page]]
  on GitHub.

  If you've created your own plugins, feel free to include it in that list.

* Creating your own plugins

** Sample Nitrogen Plugin

  The simplest way to create your own plugin is to start with the
  [[https://github.com/choptastic/sample_nitrogen_plugin][Sample Nitrogen Plugin]]
  and expand on it to make your own plugin.

** Creating your plugin from scratch

   Creating a reusable plugin from scratch is a relatively simple task, and it
   requires following the following steps:

   1) A Nitrogen plugin must be a valid Erlang application, that is, it has
      either a .app file in the ebin directory, or a .app.src file in the src
      directory.

   2) In order for Nitrogen to determine that an application is indeed a
      Nitrogen plugin, the root of your plugin must contain the file
      =nitrogen.plugin=. This file can be blank.

   3) Place and static resources in a directory in the root of the plugin
      and call that directory =static=.

   4) Place any necessary Erlang header files (e.g. if this plugin contains
      custom elements or actions) in a directory in the root of the plugin
      and call it =include=.

   5) Finally, place your plugin's Erlang source code in the =src= directory.

* See Also

  + [[./config.org][Configuration Options]]

  + [[https://github.com/choptastic/sample_nitrogen_plugin][Sample Nitrogen Plugin]]
